
package com.mindbodyonline.clients.svSale;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Sale_x0020_ServiceSoap", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SaleX0020ServiceSoap {


    /**
     * Gets a list of card types that the site accepts.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetAcceptedCardTypeResult
     */
    @WebMethod(operationName = "GetAcceptedCardType", action = "http://clients.mindbodyonline.com/api/0_5/GetAcceptedCardType")
    @WebResult(name = "GetAcceptedCardTypeResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetAcceptedCardType", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetAcceptedCardType")
    @ResponseWrapper(localName = "GetAcceptedCardTypeResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetAcceptedCardTypeResponse")
    public GetAcceptedCardTypeResult getAcceptedCardType(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetAcceptedCardTypeRequest request);

    /**
     * Validates and completes a sale by processing all items added to a shopping cart.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.CheckoutShoppingCartResult
     */
    @WebMethod(operationName = "CheckoutShoppingCart", action = "http://clients.mindbodyonline.com/api/0_5/CheckoutShoppingCart")
    @WebResult(name = "CheckoutShoppingCartResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "CheckoutShoppingCart", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.CheckoutShoppingCart")
    @ResponseWrapper(localName = "CheckoutShoppingCartResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.CheckoutShoppingCartResponse")
    public CheckoutShoppingCartResult checkoutShoppingCart(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        CheckoutShoppingCartRequest request);

    /**
     * Gets a list of sales.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetSalesResult
     */
    @WebMethod(operationName = "GetSales", action = "http://clients.mindbodyonline.com/api/0_5/GetSales")
    @WebResult(name = "GetSalesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetSales", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetSales")
    @ResponseWrapper(localName = "GetSalesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetSalesResponse")
    public GetSalesResult getSales(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetSalesRequest request);

    /**
     * Gets a list of services available for sale.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetServicesResult
     */
    @WebMethod(operationName = "GetServices", action = "http://clients.mindbodyonline.com/api/0_5/GetServices")
    @WebResult(name = "GetServicesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetServices", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetServices")
    @ResponseWrapper(localName = "GetServicesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetServicesResponse")
    public GetServicesResult getServices(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetServicesRequest request);

    /**
     * Update select services information.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.UpdateServicesResult
     */
    @WebMethod(operationName = "UpdateServices", action = "http://clients.mindbodyonline.com/api/0_5/UpdateServices")
    @WebResult(name = "UpdateServicesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "UpdateServices", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.UpdateServices")
    @ResponseWrapper(localName = "UpdateServicesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.UpdateServicesResponse")
    public UpdateServicesResult updateServices(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        UpdateServicesRequest request);

    /**
     * Gets a list of packages available for sale.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetPackagesResult
     */
    @WebMethod(operationName = "GetPackages", action = "http://clients.mindbodyonline.com/api/0_5/GetPackages")
    @WebResult(name = "GetPackagesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetPackages", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetPackages")
    @ResponseWrapper(localName = "GetPackagesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetPackagesResponse")
    public GetPackagesResult getPackages(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetPackagesRequest request);

    /**
     * Get a list of products available for sale.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetProductsResult
     */
    @WebMethod(operationName = "GetProducts", action = "http://clients.mindbodyonline.com/api/0_5/GetProducts")
    @WebResult(name = "GetProductsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetProducts", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetProducts")
    @ResponseWrapper(localName = "GetProductsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetProductsResponse")
    public GetProductsResult getProducts(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetProductsRequest request);

    /**
     * Update select products information.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.UpdateProductsResult
     */
    @WebMethod(operationName = "UpdateProducts", action = "http://clients.mindbodyonline.com/api/0_5/UpdateProducts")
    @WebResult(name = "UpdateProductsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "UpdateProducts", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.UpdateProducts")
    @ResponseWrapper(localName = "UpdateProductsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.UpdateProductsResponse")
    public UpdateProductsResult updateProducts(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        UpdateProductsRequest request);

    /**
     * Redeem a Spa Finder Gift Card.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.RedeemSpaFinderWellnessCardResult
     */
    @WebMethod(operationName = "RedeemSpaFinderWellnessCard", action = "http://clients.mindbodyonline.com/api/0_5/RedeemSpaFinderWellnessCard")
    @WebResult(name = "RedeemSpaFinderWellnessCardResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "RedeemSpaFinderWellnessCard", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.RedeemSpaFinderWellnessCard")
    @ResponseWrapper(localName = "RedeemSpaFinderWellnessCardResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.RedeemSpaFinderWellnessCardResponse")
    public RedeemSpaFinderWellnessCardResult redeemSpaFinderWellnessCard(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        RedeemSpaFinderWellnessCardRequest request);

    /**
     * Gets a list of Custom Payment Methods.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetCustomPaymentMethodsResult
     */
    @WebMethod(operationName = "GetCustomPaymentMethods", action = "http://clients.mindbodyonline.com/api/0_5/GetCustomPaymentMethods")
    @WebResult(name = "GetCustomPaymentMethodsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetCustomPaymentMethods", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetCustomPaymentMethods")
    @ResponseWrapper(localName = "GetCustomPaymentMethodsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetCustomPaymentMethodsResponse")
    public GetCustomPaymentMethodsResult getCustomPaymentMethods(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetCustomPaymentMethodsRequest request);

}
