
package com.mindbodyonline.clients.svAppointment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Appointment_x0020_ServiceSoap", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AppointmentX0020ServiceSoap {


    /**
     * Gets a list of appointments that a given staff member is instructing.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetStaffAppointmentsResult
     */
    @WebMethod(operationName = "GetStaffAppointments", action = "http://clients.mindbodyonline.com/api/0_5/GetStaffAppointments")
    @WebResult(name = "GetStaffAppointmentsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetStaffAppointments", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetStaffAppointments")
    @ResponseWrapper(localName = "GetStaffAppointmentsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetStaffAppointmentsResponse")
    public GetStaffAppointmentsResult getStaffAppointments(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetStaffAppointmentsRequest request);

    /**
     * Adds or updates a list of appointments.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.AddOrUpdateAppointmentsResult
     */
    @WebMethod(operationName = "AddOrUpdateAppointments", action = "http://clients.mindbodyonline.com/api/0_5/AddOrUpdateAppointments")
    @WebResult(name = "AddOrUpdateAppointmentsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "AddOrUpdateAppointments", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.AddOrUpdateAppointments")
    @ResponseWrapper(localName = "AddOrUpdateAppointmentsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.AddOrUpdateAppointmentsResponse")
    public AddOrUpdateAppointmentsResult addOrUpdateAppointments(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddOrUpdateAppointmentsRequest request);

    /**
     * Gets a list of bookable items.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetBookableItemsResult
     */
    @WebMethod(operationName = "GetBookableItems", action = "http://clients.mindbodyonline.com/api/0_5/GetBookableItems")
    @WebResult(name = "GetBookableItemsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetBookableItems", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetBookableItems")
    @ResponseWrapper(localName = "GetBookableItemsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetBookableItemsResponse")
    public GetBookableItemsResult getBookableItems(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetBookableItemsRequest request);

    /**
     * Gets a list of scheduled items (appointments, availabilities, and unavailabilities).
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetScheduleItemsResult
     */
    @WebMethod(operationName = "GetScheduleItems", action = "http://clients.mindbodyonline.com/api/0_5/GetScheduleItems")
    @WebResult(name = "GetScheduleItemsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetScheduleItems", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetScheduleItems")
    @ResponseWrapper(localName = "GetScheduleItemsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetScheduleItemsResponse")
    public GetScheduleItemsResult getScheduleItems(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetScheduleItemsRequest request);

    /**
     * Adds or updates a list of availabilities.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.AddOrUpdateAvailabilitiesResult
     */
    @WebMethod(operationName = "AddOrUpdateAvailabilities", action = "http://clients.mindbodyonline.com/api/0_5/AddOrUpdateAvailabilities")
    @WebResult(name = "AddOrUpdateAvailabilitiesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "AddOrUpdateAvailabilities", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.AddOrUpdateAvailabilities")
    @ResponseWrapper(localName = "AddOrUpdateAvailabilitiesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.AddOrUpdateAvailabilitiesResponse")
    public AddOrUpdateAvailabilitiesResult addOrUpdateAvailabilities(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddOrUpdateAvailabilitiesRequest request);

    /**
     * Gets a list of times that are active for a given program ID.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetActiveSessionTimesResult
     */
    @WebMethod(operationName = "GetActiveSessionTimes", action = "http://clients.mindbodyonline.com/api/0_5/GetActiveSessionTimes")
    @WebResult(name = "GetActiveSessionTimesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetActiveSessionTimes", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetActiveSessionTimes")
    @ResponseWrapper(localName = "GetActiveSessionTimesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetActiveSessionTimesResponse")
    public GetActiveSessionTimesResult getActiveSessionTimes(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetActiveSessionTimesRequest request);

    /**
     * Gets a list appointment options.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetAppointmentOptionsResult
     */
    @WebMethod(operationName = "GetAppointmentOptions", action = "http://clients.mindbodyonline.com/api/0_5/GetAppointmentOptions")
    @WebResult(name = "GetAppointmentOptionsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetAppointmentOptions", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetAppointmentOptions")
    @ResponseWrapper(localName = "GetAppointmentOptionsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetAppointmentOptionsResponse")
    public GetAppointmentOptionsResult getAppointmentOptions(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetAppointmentOptionsRequest request);

}
