
package com.mindbodyonline.clients.svFinder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Provides methods and attributes relating to clients.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Finder_x0020_Service", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", wsdlLocation = "https://api.mindbodyfinder.com/0_5/FinderService.asmx?wsdl")
public class FinderX0020Service
    extends Service
{

    private final static URL FINDERX0020SERVICE_WSDL_LOCATION;
    private final static WebServiceException FINDERX0020SERVICE_EXCEPTION;
    private final static QName FINDERX0020SERVICE_QNAME = new QName("http://clients.mindbodyonline.com/api/0_5", "Finder_x0020_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.mindbodyfinder.com/0_5/FinderService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FINDERX0020SERVICE_WSDL_LOCATION = url;
        FINDERX0020SERVICE_EXCEPTION = e;
    }

    public FinderX0020Service() {
        super(__getWsdlLocation(), FINDERX0020SERVICE_QNAME);
    }

    public FinderX0020Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FINDERX0020SERVICE_QNAME, features);
    }

    public FinderX0020Service(URL wsdlLocation) {
        super(wsdlLocation, FINDERX0020SERVICE_QNAME);
    }

    public FinderX0020Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FINDERX0020SERVICE_QNAME, features);
    }

    public FinderX0020Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FinderX0020Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FinderX0020ServiceSoap
     */
    @WebEndpoint(name = "Finder_x0020_ServiceSoap")
    public FinderX0020ServiceSoap getFinderX0020ServiceSoap() {
        return super.getPort(new QName("http://clients.mindbodyonline.com/api/0_5", "Finder_x0020_ServiceSoap"), FinderX0020ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FinderX0020ServiceSoap
     */
    @WebEndpoint(name = "Finder_x0020_ServiceSoap")
    public FinderX0020ServiceSoap getFinderX0020ServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://clients.mindbodyonline.com/api/0_5", "Finder_x0020_ServiceSoap"), FinderX0020ServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FINDERX0020SERVICE_EXCEPTION!= null) {
            throw FINDERX0020SERVICE_EXCEPTION;
        }
        return FINDERX0020SERVICE_WSDL_LOCATION;
    }

}
