
package com.mindbodyonline.clients.svFinder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Finder_x0020_ServiceSoap", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FinderX0020ServiceSoap {


    /**
     * Gets finder classes within a given radius.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetClassesWithinRadiusResult
     */
    @WebMethod(operationName = "GetClassesWithinRadius", action = "http://clients.mindbodyonline.com/api/0_5/GetClassesWithinRadius")
    @WebResult(name = "GetClassesWithinRadiusResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetClassesWithinRadius", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetClassesWithinRadius")
    @ResponseWrapper(localName = "GetClassesWithinRadiusResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetClassesWithinRadiusResponse")
    public GetClassesWithinRadiusResult getClassesWithinRadius(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetClassesWithinRadiusRequest request);

    /**
     * Gets finder classes within a given radius.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetSessionTypesWithinRadiusResult
     */
    @WebMethod(operationName = "GetSessionTypesWithinRadius", action = "http://clients.mindbodyonline.com/api/0_5/GetSessionTypesWithinRadius")
    @WebResult(name = "GetSessionTypesWithinRadiusResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetSessionTypesWithinRadius", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetSessionTypesWithinRadius")
    @ResponseWrapper(localName = "GetSessionTypesWithinRadiusResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetSessionTypesWithinRadiusResponse")
    public GetSessionTypesWithinRadiusResult getSessionTypesWithinRadius(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetSessionTypesWithinRadiusRequest request);

    /**
     * Gets available locations within a given radius.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetBusinessLocationsWithinRadiusResult
     */
    @WebMethod(operationName = "GetBusinessLocationsWithinRadius", action = "http://clients.mindbodyonline.com/api/0_5/GetBusinessLocationsWithinRadius")
    @WebResult(name = "GetBusinessLocationsWithinRadiusResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetBusinessLocationsWithinRadius", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetBusinessLocationsWithinRadius")
    @ResponseWrapper(localName = "GetBusinessLocationsWithinRadiusResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetBusinessLocationsWithinRadiusResponse")
    public GetBusinessLocationsWithinRadiusResult getBusinessLocationsWithinRadius(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetBusinessLocationsWithinRadiusRequest request);

    /**
     * Validates and completes a sale by processing all items added to a shopping cart.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.FinderCheckoutShoppingCartResult
     */
    @WebMethod(operationName = "FinderCheckoutShoppingCart", action = "http://clients.mindbodyonline.com/api/0_5/FinderCheckoutShoppingCart")
    @WebResult(name = "FinderCheckoutShoppingCartResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "FinderCheckoutShoppingCart", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.FinderCheckoutShoppingCart")
    @ResponseWrapper(localName = "FinderCheckoutShoppingCartResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.FinderCheckoutShoppingCartResponse")
    public FinderCheckoutShoppingCartResult finderCheckoutShoppingCart(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        FinderCheckoutShoppingCartRequest request);

    /**
     * Adds a Finder user. If a site ID and a location ID are provided the client will also be added to the site.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.AddOrUpdateFinderUsersResult
     */
    @WebMethod(operationName = "AddOrUpdateFinderUsers", action = "http://clients.mindbodyonline.com/api/0_5/AddOrUpdateFinderUsers")
    @WebResult(name = "AddOrUpdateFinderUsersResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "AddOrUpdateFinderUsers", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.AddOrUpdateFinderUsers")
    @ResponseWrapper(localName = "AddOrUpdateFinderUsersResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.AddOrUpdateFinderUsersResponse")
    public AddOrUpdateFinderUsersResult addOrUpdateFinderUsers(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddOrUpdateFinderUsersRequest request);

    /**
     * Gets a Finder user.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetFinderUserResult
     */
    @WebMethod(operationName = "GetFinderUser", action = "http://clients.mindbodyonline.com/api/0_5/GetFinderUser")
    @WebResult(name = "GetFinderUserResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetFinderUser", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetFinderUser")
    @ResponseWrapper(localName = "GetFinderUserResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetFinderUserResponse")
    public GetFinderUserResult getFinderUser(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetFinderUserRequest request);

    /**
     * Sends the finder user a new password.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.SendFinderUserNewPasswordResult
     */
    @WebMethod(operationName = "SendFinderUserNewPassword", action = "http://clients.mindbodyonline.com/api/0_5/SendFinderUserNewPassword")
    @WebResult(name = "SendFinderUserNewPasswordResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "SendFinderUserNewPassword", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.SendFinderUserNewPassword")
    @ResponseWrapper(localName = "SendFinderUserNewPasswordResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.SendFinderUserNewPasswordResponse")
    public SendFinderUserNewPasswordResult sendFinderUserNewPassword(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        SendFinderUserNewPasswordRequest request);

}
