/**
 *  CONFIDENTIAL
 *  
 *  All rights reserved by Brndbot, Ltd. 2014
 */
package com.mindbodyonline.clients.svStaff;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Staff_x0020_ServiceSoap", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StaffX0020ServiceSoap {


    /**
     * Gets a list of staff members.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetStaffResult
     */
    @WebMethod(operationName = "GetStaff", action = "http://clients.mindbodyonline.com/api/0_5/GetStaff")
    @WebResult(name = "GetStaffResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetStaff", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetStaff")
    @ResponseWrapper(localName = "GetStaffResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetStaffResponse")
    public GetStaffResult getStaff(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetStaffRequest request);

    /**
     * Gets a list of staff permissions based on the given staff member.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetStaffPermissionsResult
     */
    @WebMethod(operationName = "GetStaffPermissions", action = "http://clients.mindbodyonline.com/api/0_5/GetStaffPermissions")
    @WebResult(name = "GetStaffPermissionsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetStaffPermissions", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetStaffPermissions")
    @ResponseWrapper(localName = "GetStaffPermissionsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetStaffPermissionsResponse")
    public GetStaffPermissionsResult getStaffPermissions(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetStaffPermissionsRequest request);

    /**
     * Add or update staff.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.AddOrUpdateStaffResult
     */
    @WebMethod(operationName = "AddOrUpdateStaff", action = "http://clients.mindbodyonline.com/api/0_5/AddOrUpdateStaff")
    @WebResult(name = "AddOrUpdateStaffResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "AddOrUpdateStaff", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.AddOrUpdateStaff")
    @ResponseWrapper(localName = "AddOrUpdateStaffResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.AddOrUpdateStaffResponse")
    public AddOrUpdateStaffResult addOrUpdateStaff(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        AddOrUpdateStaffRequest request);

    /**
     * Gets a staff member's image URL if it exists.
     * 
     * @param request
     * @return
     *     returns com.mindbodyonline.clients.api._0_5.GetStaffImgURLResult
     */
    @WebMethod(operationName = "GetStaffImgURL", action = "http://clients.mindbodyonline.com/api/0_5/GetStaffImgURL")
    @WebResult(name = "GetStaffImgURLResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetStaffImgURL", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetStaffImgURL")
    @ResponseWrapper(localName = "GetStaffImgURLResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.mindbodyonline.clients.api._0_5.GetStaffImgURLResponse")
    public GetStaffImgURLResult getStaffImgURL(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetStaffImgURLRequest request);

}
